--- #YAML:1.0
name:                Gtk2-Ex-Clock
version:             7
abstract:            Simple digital clock widget.
license:             gpl
author:              
    - Kevin Ryde <user42@zip.com.au>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Gtk2:                          1.200
    Scalar::Util:                  0
    Tie::TZ:                       0
    Time::HiRes:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
no_index:
    directory:
        - devel
resources:
    homepage: http://www.geocities.com/user42_kevin/gtk2-ex-clock/index.html
