--- #YAML:1.0
name:                Gtk2-Ex-Clock
version:             9
abstract:            Simple digital clock widget.
license:             gpl
author:              
    - Kevin Ryde <user42@zip.com.au>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Glib:                          0
    Gtk2:                          1.200
    Tie::TZ:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
recommends:
    DateTime: 0
    DateTime::TimeZone: 0
optional_features:
    maximum_examples:
        description: Be able to run all the example programs.
        requires:
            DateTime: 0
            DateTime::TimeZone: 0
            DateTimeX::AATW: 0
    maximum_tests:
        description: Have "make test" do as much as possible.
        requires:
            Parse::CPAN::Meta: 0
            Test::Pod: 0
            Test::NoWarnings: 0
            Test::Weaken: 0
            Test::YAML::Meta: 0
            YAML: 0
            YAML::Syck: 0
            YAML::Tiny: 0
            YAML::XS: 0
no_index:
    directory:
        - devel
resources:
    homepage: http://www.geocities.com/user42_kevin/gtk2-ex-clock/index.html
    license: http://www.gnu.org/licenses/#GPL
