--- #YAML:1.0
name:               Gtk2-Ex-Clock
version:            11
abstract:           Simple digital clock widget.
author:
    - Kevin Ryde <user42@zip.com.au>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Glib:         0
    Gtk2:         1.200
    POSIX::Wide:  2
    Tie::TZ:      0
resources:
    homepage:  http://user42.tuxfamily.org/gtk2-ex-clock/index.html
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
        - devel
        - examples
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
optional_features:
    maximum_devel:
        description:  Stuff used variously for development.
        requires:
            Devel::FindRef:       0
            Devel::Peek:          0
            Devel::StackTrace:    0
            Glib::Ex::ConnectProperties:  0
            Pod::Simple::HTML:    0
    maximum_examples:
        description:  Be able to run all the example programs.
        requires:
            DateTime:            0
            DateTime::TimeZone:  0
            DateTimeX::AATW:     0
    maximum_tests:
        description:  Have "make test" do as much as possible.
        requires:
            File::Spec:          0
            FindBin:             0
            Parse::CPAN::Meta:   0
            Test::DistManifest:  0
            Test::NoWarnings:    0
            Test::Pod:           1.00
            Test::Weaken:        2.000
            Test::YAML::Meta:    0.13
            YAML:                0
            YAML::Syck:          0
            YAML::Tiny:          0
            YAML::XS:            0
recommends:
    DateTime:            0
    DateTime::TimeZone:  0
